const ONE_MIN_IN_SECONDS = 60;
const ONE_HOUR_IN_SECONDS = ONE_MIN_IN_SECONDS * 60;
const ONE_DAY_IN_SECONDS = ONE_HOUR_IN_SECONDS * 24;

module.exports = {
  ONE_MIN_IN_SECONDS,
  ONE_HOUR_IN_SECONDS,
  ONE_DAY_IN_SECONDS,
}